### ISSUE TITLE
Migration Guide from ink! 3.0 to 4.0

### ISSUE THREAD

**Issue by HCastano** [paritytech/ink-docs#112]
There are a few breaking changes between ink! 3.0 and 4.0. We should write a small guide
about what some of these changes are to make the transition easier for developers.

Non-exhaustive list of things to cover:
- Removal of storage traits (`SpreadLayout` et.al)
- New storage macros
- `CallBuilder`/`CreateBuilder` changes
- ABI changes (`version`, `lang_error`, etc.)
- Results from Constructors

**Comment by wottpal** [comment]
* imports simplified to `ink` only
* `use ink_lang as ink` obsolete
* contracts can be built on stable toolchain

**Comment by cmichi** [comment]
@wottpal We've added an elaborate migration guide here: https://use.ink/getting-started/migrating-from-ink-3-to-4.

Please let us know if you find anything missing!

**Comment by wottpal** [comment]
@cmichi That's awesome, happy to hear :)
