### ISSUE TITLE
[Metadata] Document our Metadata Format

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink-docs#12]
Currently this is the only information in the docs wrt our metadata format: https://paritytech.github.io/ink-docs/getting-started/building-your-contract/.

We should have a dedicated section which explains the format and its intention in more depth. Ideally we would have a typical `foo.contract` and just explain every key-value pair.

**Comment by cmichi** [comment]
Just noticed that the metadata example code in the page linked above is outdated as well, this example JSON should be updated as part of this ticket as well.

**Comment by SkymanOne** [comment]
already documented https://use.ink/basics/metadata
