### ISSUE TITLE
Improve search for content under different ink! version

### ISSUE THREAD

**Issue by wottpal** [paritytech/ink-docs#181]
Hey there, at the moment (at least for me), the search bar in the upper right returns results for both documented ink! versions (3 & 4). And it doesn't even highlight the version. I find it quite counter-intuitive (esp. for newbies) accidentally switching to an earlier version of the documentation without even noticing.

IMO, it should either highlight the version next to the results or (preferred) search should be only within the currently active version of the documentation.

**Comment by cmichi** [comment]
Oh boi, thanks for reporting this, I never noticed.

I just fixed it, but I'm not super-happy about it. The plugin that we use is just not that mature.  I've created this follow-up: https://github.com/paritytech/ink-docs/issues/184.
