### ISSUE TITLE
Packed and spread storage svg links are broken

### ISSUE THREAD

**Issue by forgetso** [paritytech/ink-docs#25]
The SVG links at [this](https://paritytech.github.io/ink-docs/datastructures/spread-packed-layout/) page are broken:

- https://paritytech.github.io/ink-docs/datastructures/img/spread.svg
- https://paritytech.github.io/ink-docs/datastructures/img/packed.svg

**Comment by cmichi** [comment]
You can use https://paritytech.github.io/ink-docs/datastructures/spread-packed-layout (the URL without the slash) in the meantime. They work there. This is currently the issue here: https://github.com/paritytech/ink-docs/issues/14, unfortunately.

**Comment by forgetso** [comment]
Thanks for the tip.

**Comment by cmichi** [comment]
I've hotfixed this with absolute paths for now.
