### ISSUE TITLE
Example code in documentation not working.

### ISSUE THREAD

**Issue by varshney565** [paritytech/ink-docs#275]
https://use.ink/basics/trait-definitions

None of the code in the trait definition is working.

The code of the first example is giving the error `ink! trait definitions must not have constructors` as shown in the screenshot below. 

And When I hover over the code the error given by the analyzer is 
```
All ink! trait definition methods must be ink! messages.
Invalid scope for an #[ink(constructor)] item.
```

![Screenshot from 2023-09-08 10-46-26](https://github.com/paritytech/ink-docs/assets/87566789/e4781245-2b13-41ec-9098-cc59748e01f2)

![New](https://github.com/paritytech/ink-docs/assets/87566789/cf084b9b-5365-47c8-a5b3-14084ca4ad8c)

I have tried switching to the version `4.x.x` still got the same error, is there something wrong with the documentation or am I doing it wrong

**Comment by davidsemakula** [comment]
@varshney565 Not sure if you still need this clarification, but the documentation is indeed wrong in this case.
See https://github.com/paritytech/ink-docs/pull/281 for details.

You can also use [this other example](https://github.com/paritytech/ink-examples/blob/main/trait-erc20/lib.rs) instead.

**Comment by cmichi** [comment]
Has been fixed with https://github.com/paritytech/ink-docs/pull/281.
