### ISSUE TITLE
Discuss PSPs that relate to ink in FAQ and as appropriate in tutoials/examples

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/ink-docs#34]
More context: https://github.com/substrate-developer-hub/substrate-docs/issues/460

I assume this will be the "canonical" place for contract standards to emerge, as PSP22 is directly related here?

I would think that highlighting in the FAQ something about "what is the `ERC####` equivalent for ink & contracts pallet?" or "what contract standards exist?" that directs to PSPs would be a good staring point :grin:

**Comment by SkymanOne** [comment]
Already addressed in https://use.ink/getting-started/use-openbrush
