### ISSUE TITLE
Deprecated string Selector instructions shown in docs

### ISSUE THREAD

**Issue by justinFrevert** [paritytech/ink-docs#36]
[This page](https://paritytech.github.io/ink-docs/macros-attributes/selector) (among others) shows deprecated instructions for specifying a Selector. 

When trying to create a Selector with the following syntax `selector = "0xDEADBEEF"` on cargo contracts 0.15, the error received is: `#[ink(selector = ..)] attributes with string inputs are deprecated. use an integer instead, e.g. #[ink(selector = 1)] or #[ink(selector = 0xC0DECAFE)`. The docs should probably make mention of the deprecation and offer an up-to-date suggestion.

**Comment by SkymanOne** [comment]
Closing as outdated
