### ISSUE TITLE
Describe new constructor default payable behaviour

### ISSUE THREAD

**Issue by HCastano** [paritytech/ink-docs#41]
Before https://github.com/paritytech/ink/pull/1065 constructors in ink! were `payable` (that is, they accepted a `value`) by default. For reasons described in that PR this is no longer the default behaviour. 

Now, constructors will need to opt into accepting a `value` through the use of the already existing `#[ink(payable)]` attribute.

**Comment by SkymanOne** [comment]
Closing as outdated
