### ISSUE TITLE
Canvas UI having a maintenance problem 

### ISSUE THREAD

**Issue by omarelweshy** [paritytech/ink-docs#45]
I tried to use Canvas UI like docs but I found that they have a problem [here](https://github.com/paritytech/canvas-ui/issues/119#issuecomment-1020114242) and advised to use [polkadot](https://polkadot.js.org/apps/#/contracts).

**Comment by SkymanOne** [comment]
Closing as Canvas has been deprecated. Please use https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.24.0 and https://contracts-ui.substrate.io/ for local testing and [Rococo-network](https://substrate.io/developers/rococo-network/) as a devnet
