### ISSUE TITLE
Mention new `cargo-contract` commands for contract on-chain interaction

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink-docs#56]
Mention the new `cargo-contract` commands for CLI contract interaction:

* `cargo contract upload`
* `cargo contract instantiate`
* `cargo contract call`

See `https://github.com/paritytech/cargo-contract#usage` or `cargo contract --help` for more info.

**Comment by SkymanOne** [comment]
Mentioned here https://use.ink/getting-started/deploy-your-contract#using-cargo-contract
